env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: true
  tsconfigRootDir: '.'
plugins:
  - '@typescript-eslint'
rules:
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
